改善item22部分语句，使之更符合中文语义，更通顺
CnTransGroup/EffectiveModernCppChinese pull request #136
Opened 2022-11-14 13:20 UTC by L-Super

当我在阅读item22章节时，发现部分语句实在是比较生硬，所以擅自润饰了一下。

```
但是，如果你想强调编译器生成的析构函数会做正确的事情——你声明`Widget`的析构函数的唯一原因是导致它的定义在 Widget 的实现文件中（译者注：指`widget.cpp`）生成，你可以使用“`= default`”定义析构函数体：
```
些许遗憾的是，上述语句仍未达到理想的效果。

部分词汇也改为了更通用的词，比如深浅拷贝。

2022-11-18 14:11 UTC, kelthuzadx requested changes
感谢校对～有一处改动有待商榷

2022-11-18 14:11 UTC, kelthuzadx commented on src/4.SmartPointers/item22.md
> +这样就可以了，并且这样增加的代码也最少，但是，如果你想强调编译器生成的析构函数会做正确的事情——你声明`Widget`的析构函数的唯一原因是导致它的定义在 Widget 的实现文件中（译者注：指`widget.cpp`）生成，你可以使用“`= default`”定义析构函数体：
听起来原翻译更流畅

2022-11-18 14:37 UTC, L-Super commented on src/4.SmartPointers/item22.md
> +这样就可以了，并且这样增加的代码也最少，但是，如果你想强调编译器生成的析构函数会做正确的事情——你声明`Widget`的析构函数的唯一原因是导致它的定义在 Widget 的实现文件中（译者注：指`widget.cpp`）生成，你可以使用“`= default`”定义析构函数体：
这一处确实，当时自已也觉得翻译的不甚理想

2022-11-18 17:26 UTC, kelthuzadx commented on src/4.SmartPointers/item22.md
> +这样就可以了，并且这样增加的代码也最少，但是，如果你想强调编译器生成的析构函数会做正确的事情——你声明`Widget`的析构函数的唯一原因是为了在 Widget 的实现文件中（译者注：指`widget.cpp`）生成它的定义，你可以使用“`= default`”定义析构函数体：
```suggestion
这样就可以了，并且这样增加的代码也最少，你声明`Widget`析构函数只是为了在 Widget 的实现文件中（译者注：指`widget.cpp`）写出它的定义，但是如果你想强调编译器自动生成的析构函数会做和你一样正确的事情，你可以直接使用“`= default`”定义析构函数体
```

2022-11-19 13:07 UTC, kelthuzadx commented on src/4.SmartPointers/item22.md
> +这样就可以了，并且这样增加的代码也最少，但是，如果你想强调编译器生成的析构函数会做正确的事情——你声明`Widget`的析构函数的唯一原因是为了在 Widget 的实现文件中（译者注：指`widget.cpp`）生成它的定义，你可以使用“`= default`”定义析构函数体：
这样是否更通顺

2022-11-19 13:34 UTC, L-Super commented on src/4.SmartPointers/item22.md
> +这样就可以了，并且这样增加的代码也最少，但是，如果你想强调编译器生成的析构函数会做正确的事情——你声明`Widget`的析构函数的唯一原因是为了在 Widget 的实现文件中（译者注：指`widget.cpp`）生成它的定义，你可以使用“`= default`”定义析构函数体：
通顺，赞同修改

2022-11-19 14:13 UTC, merged